// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4o1-8dZIeGVigl4bpGPnWCAwGOry6-A',
    appId: '1:466189850301:web:567bee628274e1a31089d4',
    messagingSenderId: '466189850301',
    projectId: 'school-7e98a',
    authDomain: 'school-7e98a.firebaseapp.com',
    storageBucket: 'school-7e98a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9LN3v7bLsxxVhXU7BPF78noSgzCr1O7U',
    appId: '1:466189850301:android:0547cad425e720e21089d4',
    messagingSenderId: '466189850301',
    projectId: 'school-7e98a',
    storageBucket: 'school-7e98a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtTt_jTKmjFc5OFbkLpeCu6cyTjH4DuFs',
    appId: '1:466189850301:ios:86a8f28507bd1f881089d4',
    messagingSenderId: '466189850301',
    projectId: 'school-7e98a',
    storageBucket: 'school-7e98a.firebasestorage.app',
    iosBundleId: 'com.example.school',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtTt_jTKmjFc5OFbkLpeCu6cyTjH4DuFs',
    appId: '1:466189850301:ios:86a8f28507bd1f881089d4',
    messagingSenderId: '466189850301',
    projectId: 'school-7e98a',
    storageBucket: 'school-7e98a.firebasestorage.app',
    iosBundleId: 'com.example.school',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg4o1-8dZIeGVigl4bpGPnWCAwGOry6-A',
    appId: '1:466189850301:web:5276fcf9d5969c6a1089d4',
    messagingSenderId: '466189850301',
    projectId: 'school-7e98a',
    authDomain: 'school-7e98a.firebaseapp.com',
    storageBucket: 'school-7e98a.firebasestorage.app',
  );
}
